// Copyright (c) Ehsan. Licensed under the MIT License.
using System.Collections.ObjectModel;

namespace WebhookKit.Abstractions;

/// <summary>
/// Persistent or in-flight representation of an ingested webhook delivery.
/// <see cref="RawBody"/> is the byte-for-byte source of truth for signature verification.
/// </summary>
public sealed class WebhookRecord
{
    private static readonly IReadOnlyDictionary<string, IReadOnlyList<string>> EmptyHeaders =
        new ReadOnlyDictionary<string, IReadOnlyList<string>>(
            new Dictionary<string, IReadOnlyList<string>>(StringComparer.OrdinalIgnoreCase));

    private IReadOnlyDictionary<string, IReadOnlyList<string>> _headers = EmptyHeaders;
    private string? _correlationId;
    /// <summary>ULID-formatted identifier generated by WebhookKit per HTTP transmission.</summary>
    public required string Id { get; init; }

    /// <summary>Application correlation identifier, or a generated value when none was supplied.</summary>
    public string CorrelationId
    {
        get
        {
            var correlationId = _correlationId;
            if (correlationId is not null)
            {
                return correlationId;
            }

            var generated = CreateCorrelationId();
            return Interlocked.CompareExchange(ref _correlationId, generated, null) ?? generated;
        }
        init => _correlationId = string.IsNullOrWhiteSpace(value) ? null : value.Trim();
    }

    /// <summary>Configured provider name (e.g. "stripe"). Case-insensitive.</summary>
    public required string Provider { get; init; }

    /// <summary>Upstream provider event identifier (e.g. "evt_123"). Null until extracted.</summary>
    public string? EventId { get; init; }

    /// <summary>Provider-scoped identity used for atomic deduplication.</summary>
    public string DeduplicationKey { get; init; } = string.Empty;

    /// <summary>Categorical event type (e.g. "payment.succeeded"). Null until extracted.</summary>
    public string? EventType { get; init; }

    /// <summary>HTTP method of the ingress request.</summary>
    public required string HttpMethod { get; init; }

    /// <summary>Request path of the ingress request.</summary>
    public required string RequestPath { get; init; }

    /// <summary>Immutable request header snapshot with multiple read-only values per key.</summary>
    public required IReadOnlyDictionary<string, IReadOnlyList<string>> Headers
    {
        get => _headers;
        init => _headers = WebhookHeaderSnapshot.Create(value);
    }

    /// <summary>Request content-type header value, if present.</summary>
    public string? ContentType { get; init; }

    /// <summary>Request content-length header value, if present.</summary>
    public long? ContentLength { get; init; }

    /// <summary>Exact unmodified raw payload bytes. Stores may copy or discard this buffer according to configuration.</summary>
    public byte[]? RawBody { get; set; }

    /// <summary>Instant the request was received, from <see cref="IWebhookClock"/>.</summary>
    public required DateTimeOffset ReceivedAt { get; init; }

    /// <summary>Provider-supplied event timestamp, if extracted and valid.</summary>
    public DateTimeOffset? ProviderTimestamp { get; init; }

    /// <summary>Current lifecycle state.</summary>
    public WebhookProcessingStatus Status { get; set; }

    /// <summary>Number of processing attempts so far.</summary>
    public int AttemptCount { get; set; }

    /// <summary>Instant the most recent processing attempt started.</summary>
    public DateTimeOffset? LastAttemptAt { get; set; }

    /// <summary>Owner of the current processing lease, when one is held.</summary>
    public string? ProcessingLeaseOwner { get; set; }

    /// <summary>Instant at which the current processing lease expires.</summary>
    public DateTimeOffset? ProcessingLeaseExpiresAt { get; set; }

    /// <summary>Instant processing completed successfully, if applicable.</summary>
    public DateTimeOffset? ProcessedAt { get; set; }

    /// <summary>Instant processing was marked failed, if applicable.</summary>
    public DateTimeOffset? FailedAt { get; set; }

    /// <summary>Non-sensitive diagnostic failure reason. Never contains secrets.</summary>
    public string? FailureReason { get; set; }

    /// <summary>Stable machine-readable failure code, when processing failed.</summary>
    public string? FailureCode { get; set; }

    private string CreateCorrelationId()
    {
        string generated;
        do
        {
            generated = Guid.NewGuid().ToString("N");
        }
        while (string.Equals(generated, Id, StringComparison.Ordinal) ||
               string.Equals(generated, EventId, StringComparison.Ordinal));

        return generated;
    }
}
